steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - cf_cloud_build
  - --region=us-central1
  - --allow-unauthenticated
  - --source=https://source.developers.google.com/projects/bigquery-fisrtsteps/repos/github_alexandreexteves_cloud-function-stack/moveable-aliases/main/paths/cf_cloud_build
  - --trigger-http
  - --runtime=python39
  - --memory=256MB
  - --project=bigquery-fisrtsteps
  - --entry-point=hello_world
  - --update-labels=course=cloud_functions,env=dev,layer=raw